version: '2.0'

services:

  db:
    image: dockersamples/k8s-wordsmith-db

  words:
    image: dockersamples/k8s-wordsmith-api

  web:
    image: dockersamples/k8s-wordsmith-web
    command: >
        bash -c "x=10
        && echo x = $x"
    ports:
     - "8080:80"
